### ISSUE TITLE
Is it possible to have both Laravel and js on same project?

### ISSUE THREAD

**Issue by tobz-nz** [facade/flare-client-js#116]
Ah, just answered my own question but going to post it anyway for others.

Yes, but its clunky - set the project as js, get the token and change it back to Laravel - setup your js client.

Would be tidier if the js token was avaialble on laravel/php settings page as well as the serverside key.

**Comment by Sam-Apostel** [comment]
We designed this flow to guide users in creating a new project for different systems. I do however like the idea of a dedicated settings page for all api keys that are active for a project.

I created a discussion on our roadmap repo: https://github.com/spatie/flareapp.io-roadmap/discussions/77
