### ISSUE TITLE
Typescript errors when building project with flare-react

### ISSUE THREAD

**Issue by dennisnotebaart** [facade/flare-client-js#117]
### Description
We have a Laravel project with an Inertia/React/TypeScript front-end. After adding the Flare React client we get TypeScript errors from the flare-react package when running `npm buid`.

I've confirmed this is also the case in a fresh project.

### Errors
```
node_modules/@flareapp/flare-react/dist/react/src/index.d.ts:6:19 
error TS2307: Cannot find module '../../client/dist/FlareClient' or its corresponding type declarations.
6     flare: import("../../client/dist/FlareClient").default | null;
```

```
node_modules/@flareapp/flare-react/dist/react/src/index.d.ts:11:96 
error TS2304: Cannot find name 'Flare'.
11 export declare function reportReactError(error: Error, reactErrorInfo: React.ErrorInfo, flare: Flare | null): void;
```

### How to reproduce

- Install new Laravel project (`laravel new react-flare-test`)
- Pick the Breeze starter kit
- Pick the React with Inertia stack
- Tick the TypeScript option
- Add the Flare JS/React packages (`npm install @flareapp/flare-client @flareapp/vite-plugin-sourcemap-uploader @flareapp/flare-react`)
- Add `flare.light()` and FlareErrorBoundary wrapper to the app root (as instructed in Flare)
- Run `npm run buid`

**Comment by ignasradzius** [comment]
Ran into the same problem. @dennisnotebaart did you manage to find a workaround?

**Comment by dennisnotebaart** [comment]
@ignasradzius I've contacted support and was told they're working on a new version of the package. You can use the vanilla JS client in the meantime.

**Comment by sebastiandedeyne** [comment]
Hi!

Thanks everyone for your patience with this issue. We just tagged a beta version of our new JavaScript packages, with stable version coming next week!

If you already want to give them a try, you can install the following packages (they've been slightly renamed):

```json
"dependencies": {
  "@flareapp/js": "^1.0.0-beta",
  "@flareapp/react": "^1.0.0-beta",
  "@flareapp/vue": "^1.0.0-beta"
},
"devDependencies": {
  "@flareapp/vite": "^1.0.0-beta"
}
```
