### ISSUE TITLE
Failing to report Nuxt server side errors

### ISSUE THREAD

**Issue by ianjamieson** [facade/flare-client-js#119]
When using `@flareapp/flare-client` with nuxt I get the following error server side.

Nuxt automatically [handles errors](https://nuxt.com/docs/getting-started/error-handling) by sending the user to the `/error.vue` component. Which I have a script setup like this:

```
<script setup lang="ts">
import { flare } from '@flareapp/flare-client';

// report error
flare.report(props.error);
</script>
<template>
...
</template>
```

However, when nuxt catches an error and redirects the user to this page, I get the following error from flare:

```
[nitro] [dev] [unhandledRejection] ReferenceError: document is not defined                                       7:58:31 AM
    at f (/Users/ianjamieson/tixel/content-nuxt/node_modules/@flareapp/flare-client/dist/index.js:1:7042)
    at /Users/ianjamieson/tixel/content-nuxt/node_modules/@flareapp/flare-client/dist/index.js:1:15761
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Now, if I only report the error client side:

```
if(process.client) {
  // report error
  flare.report(props.error);
}
```

Then the error goes away.

I have also tested to see if errors come through to flare despite the warning showing, and they don't.

I have tested by putting:

```
flare.report({
  message: `from store, client: ${process.client}`
});
```

Inside a store which is executed server side, and I do not see any error in flare, just the document undefined error.

**Comment by GioChocolateBro** [comment]
@ianjamieson you should have a look at this article: https://www.lichter.io/articles/nuxt3-sentry-recipe/. It's on integrating sentry with nuxt 3. 

As soon as the commonJS issues are fixed with the flare client I was planning on following this approach for flare. This should take care of client side and server side.

**Comment by sebastiandedeyne** [comment]
Hi!

Thanks everyone for your patience with this issue. We just tagged a beta version of our new JavaScript packages, with stable version coming next week!

The new versions are compatible with Node.js and don't require a browser environment, so they can report SSR errors.

If you already want to give them a try, you can install the following packages (they've been slightly renamed):

```json
"dependencies": {
  "@flareapp/js": "^1.0.0-beta",
  "@flareapp/react": "^1.0.0-beta",
  "@flareapp/vue": "^1.0.0-beta"
},
"devDependencies": {
  "@flareapp/vite": "^1.0.0-beta"
}
```

**Comment by ianjamieson** [comment]
Just confirming that I should replace:

`@flareapp/flare-client` with `@flareapp/js`

and

`@flareapp/flare-vue` with `@flareapp/vue`

and

`@flareapp/vite-plugin-sourcemap-uploader` with `@flareapp/vite`

**Comment by ianjamieson** [comment]
![Screenshot 2024-02-16 at 09 58 49](https://github.com/facade/flare-client-js/assets/2786904/6500073f-4ebf-435a-9b12-d88d7a240462)

**Comment by sebastiandedeyne** [comment]
Correct!

**Comment by ianjamieson** [comment]
Works perfectly, thanks.
