### ISSUE TITLE
JS Console Error: `Refused to set unsafe header "Access-Control-Request-Headers"`

### ISSUE THREAD

**Issue by mikebronner** [facade/flare-client-js#61]
I'm seeing the following error in my javascript console when developing locally (haven't tested in production yet):

```js
[Error] Refused to set unsafe header "Access-Control-Request-Headers"
	(anonymous function) (app.js:726:236)
	promiseReactionJob
```

**Comment by AdrianMrn** [comment]
FYI: we are looking into this and will update when we have decided on a fix.

**Comment by AdrianMrn** [comment]
@mikebronner I've just published a new version of the client, can you try setting your version to the newest version? `"@flareapp/flare-client": "^1.0.2"`

Please let me know if this fixes your problem.

**Comment by mikebronner** [comment]
@AdrianMrn Thanks for the update. Unfortunately I have stopped using Flare for the time being and am unable to test.

**Comment by AdrianMrn** [comment]
All right, hope to see you again soon! If you have any more questions about Flare, don't hesitate to contact us here or through email at support@flareapp.io
