### ISSUE TITLE
document CDN

### ISSUE THREAD

**Issue by AdrianMrn** [facade/flare-client-js#67]
How to set up the JS client using a CDN and a script tag. Also for the Vue & React libraries (not sure this will be possible for React, but Vue should be easy).

**Comment by tobz-nz** [comment]
Keen on this - I'm having trouble getting it to work on a legacy app with a lot of inline scripts using jquery  None of the js is compiled with webpack so the current docs aren't much use. The client is all typescript - is it possible to get a compiled version that can just be loaded with native js `import`?

**Comment by AlexVanderbist** [comment]
Hi there, for anyone looking for this. Until we properly document this, the following snippet should get you started with the Flare client using a CDN:
```
<script src="https://unpkg.com/@flareapp/flare-client@3.x.x/dist/index.js"></script>

<script>
  flare.light('your-project-token');
</script>
```
