### ISSUE TITLE
Editing the "user" context

### ISSUE THREAD

**Issue by grantholle** [facade/flare-client-js#73]
I'm currently adding a custom context, `user`, but ideally I'd like my user info to be in the actual proprietary "user" context for Flare.

Would I do something like this?

```js
flare.beforeSubmit = report => {
  const editedReport = _.cloneDeep(report)
  
  // Is it just under the `user` prop?
  editedReport.context.user = myUserObject

  return editedReport
}
```

Is there anything I should know about on how to structure the object so it plays nice?

**Comment by AdrianMrn** [comment]
Hi @grantholle!

Your method seems pretty complete!

The `User` tab doesn't come with any restrictions if you choose to edit the user context object: The entire user object will be shown as a copyable block of code. If the `user` object contains an email, Flare will also display it separately along with its gravatar image, if one exists for that email.

![image](https://user-images.githubusercontent.com/12762044/91996204-03269380-ed39-11ea-8c43-e817b62e0831.png)
